name: 'Gitleaks Scan'
description: 'Run Gitleaks to scan for sensitive information in the repository.'
inputs:
  report-path:
    description: 'The path where the Gitleaks report should be saved.'
    required: false
    default: '/github/workspace/gitleaks-report.json'
runs:
  using: 'docker'
  image: 'immutablegit/scan.latest'  # Replace with the image name and tag you built and pushed earlier
  args:
    - /github/workspace
    - ${{ inputs.report-path }}  # Using the input directly without the need for "${{ inputs.report-path }}"
