name: 'Gitleaks Scan'
description: 'Run Gitleaks to scan for sensitive information in the repository.'
inputs:
  report-path:
    description: 'The path where the Gitleaks report should be saved.'
    required: false
    default: '/results/gitleaks-report.sarif'
runs:
  using: 'docker'
  image: 'immutablegit/scan.latest'  # Replace with the image name and tag you built and pushed earlier
  env:
    REPORT_PATH: ${{ inputs.report-path }}
