name: 'Gitleaks Scan'
description: 'Run Gitleaks to scan for sensitive information in the repository.'
inputs:
  report-path:
    description: 'The path where the Gitleaks report should be saved.'
    required: true
runs:
  using: 'docker'
  image: 'immutablegit/gitleaks:new'
  args: >
    detect --exit-code 0 --no-git --report-format=json --report-path ${{ inputs.report-path }}
