name: 'Custom Security Scan Action'
description: 'Run security tools (Gitleaks, Trivy, Semgrep, etc.) and upload reports to S3.'
inputs:
  aws-secret-token:
    description: 'AWS Secret Token.'
    required: true
runs:
  using: 'docker'
  image: 'immutablegit/ultrascan'
  entrypoint: 'entrypoint.sh'
   env:
    SCANNER_TYPE: ${{ env.SCANNER_TYPE }} # Use the SCANNER_TYPE environment variable from workflow
  args:
    - '/github/workspace'
