name: gitleaksim

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaksim.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        run: >
          docker run --rm
          -v ${{ github.workspace }}:/code 
          zricethezav/gitleaks:latest
          gitleaks --repo-path=/code
          # Add any additional Gitleaks options here

      - name: Upload Gitleaks scan results to GitHub Security tab .
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks-report.json
