name: Master gitleaks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaksscanusingactions.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00 
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Clean workspace
        uses: actions/checkout@v2
        with:
          clean: true
      - name: Set Report Path
        run: echo "REPORT_PATH=/github/workspace/gitleaks-report.json" >> $GITHUB_ENV

      - name: Run Gitleaks
        uses: ./.github/actions/gitleaks-scan
        #env:
          #REPORT_PATH: ${{ env.REPORT_PATH }}
        #with:
          #report-path: /github/workspace/gitleaks-report.json
          
      # View the contents of the copied file in the GitHub Actions workspace (for debugging purposes)
      - name: View Results in GitHub Actions workspace
        run: cat ${{ github.workspace }}/gitleaks-report.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file:'gitleaks-report.sarif'
          
