name: Gitleaks Scan

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaks_no_docker.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Clean workspace
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Run Gitleaks
        uses: docker://immutablegit/gitleaks:latest
        with:
          args: detect --exit-code 1 
          # Add any additional Gitleaks options here
