name: Master gitleaks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaksscanusingactions.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00 
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Clean workspace
        uses: actions/checkout@v2
        with:
          clean: true
      - name: Set Report Path
        run: echo "REPORT_PATH=${{ github.workspace }}/gitleaks-report.json" >> $GITHUB_ENV

      - name: Run Gitleaks
        uses: ./.github/actions/gitleaks-scan
        env:
          REPORT_PATH: ${{ env.REPORT_PATH }}
        #with:
          #report-path: /github/workspace/gitleaks-report.json
          
      - name: Print Gitleaks Output 
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the repository directory :"
          ls -la
          echo "Contents of the GitHub workspace:"
          ls -la ${{ github.workspace }}
          echo "Contents of the /tmp directory:"
          ls -ld /tmp
          ls -la /tmp/gitleaks-report.json
          cat "/tmp/gitleaks-report.json"
