name: gitleaks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaks.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v13
        
      - name: Upload Gitleaks scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks-report.json
