name: Immutable.cloud Gitleaks 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/gitleaksimc.yml
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00 
    - cron: '5 10 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Clean workspace
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Run Gitleaks
        
        run: |
          docker pull immutablegit/gitleaks:new
          docker run --rm -v ${{ github.workspace }}:/code -v ${{ env.RUNNER_TEMP }}:/tmp your_custom_gitleaks_image:latest gitleaks detect --exit-code 0 --no-git --report-format=sarif --verbose > /tmp/gitleaks-report.sarif
          # Add any additional Gitleaks options here
          
        #uses: docker://immutablegit/gitleaks:new
        #with:
          #args: detect --exit-code 0 --no-git --report-format=json --verbose > gitleaks-report.json
          # Add any additional Gitleaks options here
          
      - name: Print Gitleaks Output
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the repository directory:"
          ls -la
          echo "Contents of the GitHub workspace:"
          ls -la ${{ github.workspace }}
          echo "Contents of the /tmp directory:"
          ls -la /tmp
          cat "/tmp/gitleaks-report.sarif"
 





