on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/trivy.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 5 10 * * *
name: trivy
jobs:
  trivy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: docker://immutablegit/custom-trivy-fs:latest
        with:
          args: /github/workspace/
        env:
          TRIVY_SCANNERS: "vuln,secret" # Set the desired scanners here
         # Save the container ID to an output variable
      - name: Save container ID
        run: echo "::set-output name=container_id::$(docker ps -q -n 1)"

      # Copy the ls_results.txt file from the container to the host machine
      - name: Copy Results to Host
        run: docker cp ${{ steps.Run_Trivy.outputs.container_id }}:/tmp/ls_results.txt ${{ github.workspace }}/ls_results.txt

      # View the contents of the file
      - name: View Results
        run: cat ${{ github.workspace }}/ls_results.txt

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
