on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/trivy.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 5 10 * * *
name: trivy
jobs:
  trivy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: docker://immutablegit/custom-trivy-fs:latest
        with:
          args: /github/workspace/
        env:
          TRIVY_SCANNERS: "vuln,secret" # Set the desired scanners here
     
      # View the contents of the copied file in the GitHub Actions workspace (for debugging purposes)
      - name: View Results in GitHub Actions workspace
        run: cat ${{ github.workspace }}/trivy-results.sarif

      #- name: Upload Trivy scan results to GitHub Security tab
        #uses: github/codeql-action/upload-sarif@v2
        #with:
          #sarif_file: 'trivy-results.sarif'
