on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/ultrascan.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 5 10 * * *
  
name: UltraScan

jobs:
  security_scan:
    runs-on: ubuntu-20.04
    env:
       SCANNER_TYPE: "sbom" # Set the desired scanners here - eg . vuln,sast,sbom,config 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      #- name: Set up Docker
      #  uses: docker/setup-buildx-action@v1

      - name: Run Ultrascan
        uses: ./.github/actions/ultrascan # Assumes the actions.yaml and Dockerfile are in the root of the repository
        with:
          scanner-type: ${{ env.SCANNER_TYPE }}
        env:
          AWS_SECRET_TOKEN: ${{ secrets.AWS_SECRET_TOKEN }}

